language: python
sudo: required
dist: xenial
cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - TESTDATA_DIR=$HOME/testdata

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libgdal-dev
      - gdal-bin
      - libudunits2-dev
      - libspatialite-dev
      - libsqlite3-mod-spatialite
      - swig2.0
      - libproj-dev

python:
  - '3.7'
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'

before_install:
  - wget -O esa-snap_sentinel_unix_6_0.sh https://step.esa.int/downloads/6.0/installers/esa-snap_sentinel_unix_6_0.sh
  - bash esa-snap_sentinel_unix_6_0.sh -q
  - export PATH=$PATH:/opt/snap/bin

install:
  - pip install -r requirements.txt
  # install official python bindings to libgdal
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/include/gdal
  - export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/include/gdal
  - pip install --global-option=build_ext --global-option="$(gdal-config --cflags)" gdal==$(gdal-config --version)
  # install code coverage tools
  - pip install coveralls coverage
  - python setup.py install

#before_script:
#  - travis_wait 40 . ./pyroSAR/install/download_testdata.sh

script:
  - coverage run --source pyroSAR/ -m pytest

after_success:
- coveralls

notifications:
  slack: pyrosar:bs03zodEkRSYr8MN5HrgfSeB
